[build-system]
requires = ["setuptools>=45", "wheel", "numpy>=2"]
build-backend = "setuptools.build_meta"

[project]
name = "vcztools"
description = "Implementation of bcftools for VCF Zarr"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "sgkit Developers", email = "project@sgkit.dev"},
]
dependencies = [
  "numpy>=1.23.5,<2",
  "numba",
  "zarr>=2.17,<3",
  "click",
  "pyranges",
]
requires-python = ">=3.9"
dynamic = ["version"]

[project.scripts]
vcztools = "vcztools.cli:vcztools_main"

[project.optional-dependencies]
dev = [
  "bio2zarr @ git+https://github.com/sgkit-dev/bio2zarr.git",
  "cyvcf2",
  "hypothesis-vcf @ git+https://github.com/sgkit-dev/hypothesis-vcf.git",
  "pysam",
  "pytest",
  "pytest-datadir",
]

[tool.setuptools]
packages = ["vcztools"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools_scm]
write_to = "vcztools/_version.py"
